version: '3.4'

services:
  powerplant-coding-challenge:
    image: ${DOCKER_REGISTRY-}powerplantcodingchallenge
    build:
      context: .
      dockerfile: powerplant-coding-challenge/Dockerfile
    ports:
      - 8888:443
      - 8887:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
